export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

export const FETCH_TRL_REQUEST = "FETCH_TRL_REQUEST";
export const FETCH_TRL_SUCCESS = "FETCH_TRL_SUCCESS";
export const FETCH_TRL_FAILURE = "FETCH_TRL_FAILURE";

export const FETCH_CONFIGURATION_REQUEST = "FETCH_CONFIGURATION_REQUEST";
export const FETCH_CONFIGURATION_SUCCESS = "FETCH_CONFIGURATION_SUCCESS";
export const FETCH_CONFIGURATION_FAILURE = "FETCH_CONFIGURATION_FAILURE";